---
- name: Install tmux
  apt:
    name: tmux
    state: present
  become: true
  become_method: sudo

- name: Copy tmux configuration file
  copy:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ ansible_env.HOME }}"
